system:
  version:
    number: 0.0.2


spring:
  mvc:
      # spring CORS configuration
      cors:
        mappings:
          # Intercept path
           "/api/**":
                       allowed-origins: "*"
                       allowed-methods: "*"
                       allowed-headers: "*"
                       max-age: "1800"
                       allow-credentials: "true"

  datasource:
      url: "${DATABASE_URL:jdbc:postgresql://101.200.48.242:5432/db}"
      username: "${DATABASE_USERNAME:postgres}"
      password: "${DATABASE_PASSWORD:postgres}"
      driver-class-name: "${DATABASE_DRIVER:org.postgresql.Driver}"
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml

