system:
  version:
    number: 0.0.2


spring:
  datasource:
      url: "${DATABASE_URL:jdbc:postgresql://101.200.48.242:5432/db}"
      username: "${DATABASE_USERNAME:postgres}"
      password: "${DATABASE_PASSWORD:postgres}"
      driver-class-name: "${DATABASE_DRIVER:org.postgresql.Driver}"

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml
